#---------------------------------------------------------------------
# GitHub Action Workflow for Fonda
# Version 1.1
# 2022
#---------------------------------------------------------------------

name: build
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches:
      - develop
    paths-ignore:
      - "doc/**"
      - ".github/workflows/**"
      - ".example/**"
      - ".README.md"
      - ".gitignore"
      
  pull_request:
    branches: 
      - "**"
    paths-ignore:
      - "doc/**"
      - ".github/workflows/**"
      - ".example/**"
      - ".README.md"
      - ".gitignore"
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Correcting a Build Number
        run: echo "BUILD_NUMBER=$(echo $((${{ github.run_number }}+653)))" >> $GITHUB_ENV
         
      - name: Get Current Version
        run: echo "FONDA_VERSION=$(./gradlew :printVersion -PbuildNumber=$BUILD_NUMBER |  grep "Project version is " | sed 's/^.*is //')" >> $GITHUB_ENV
      
      - name: Setup Java JDK
        uses: actions/setup-java@v2
        with:
          distribution: "temurin" # See 'Supported distributions' for available options
          java-version: "8"
      
      - name: Gradle Build Action
        uses: gradle/gradle-build-action@v2
        with:
          arguments: -PbuildNumber=${{ env.FONDA_VERSION }}.ga.${{ github.sha }} build zip --no-daemon
          
      - name: Gradle Coverage Action
        uses: gradle/gradle-build-action@v2
        with:
          arguments: jacocoTestReport
          
      - name: Upload a Build Artifact on the GitHub Actions Job page
        uses: actions/upload-artifact@v2.2.4
        with:
          name: fonda-${{ env.FONDA_VERSION }}.ga.${{ github.sha }}
          path: build/distributions/fonda*.zip
          
      - name: Upload Coverage to Codecov
        if: ${{ github.event_name == 'push' && github.ref_name == 'develop' }}
        uses: codecov/codecov-action@v2
          
      - name: Configure AWS Credentials
        if: ${{ github.event_name == 'push' && github.ref_name == 'develop' }}
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
          
      - name: Copy a Build Artifact to AWS
        if: ${{ github.event_name == 'push' && github.ref_name == 'develop' }}
        run: aws s3 cp build/distributions/fonda*.zip s3://fonda-oss-builds/builds/$GITHUB_REF_NAME/
        shell: bash
        
      - name: Create GitHub release
        if: ${{ github.event_name == 'push' && github.ref_name == 'develop' }}
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/distributions/fonda*.zip"
          tag: ${{ env.FONDA_VERSION }}
          name: Release ${{ env.FONDA_VERSION }}
          token: ${{ secrets.GITHUB_TOKEN }}
